version: '2'
services:
  web:
    build: .
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/rails
    depends_on:
      - db
  db:
    image: postgres:9.6.1
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
